application:
  port: 8000
database:
  host: "0.0.0.0"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "placeholder@gmail.com"
  auth_token: "my-secret-token"